version: "3"
volumes:
  Galleries:
  Local:
  Plugins:
  Themes:
  Cache:
  Upload:
  Mysql:
networks:
  web:
    external: true
services:
  piwigo:
    build: .
    container_name: piwigo
    volumes:
      - ${WO_DIR_GALLERIES}:/piwigo/piwigo/galleries
      - ${WO_DIR_LOCAL}:/piwigo/piwigo/local
      - ${WO_DIR_PLUGINS}:/piwigo/piwigo/plugins
      - ${WO_DIR_THEMES}:/piwigo/piwigo/themes
      - ${WO_DIR_CACHE}:/piwigo/piwigo/_data/i
      - ${WO_DIR_UPLOAD}:/piwigo/piwigo/upload
      - /var/log
      - /var/log/piwigo:/var/log/apache2
    expose:
      - "9000"
    links:
      - mysql
    labels:
      - traefik.backend=piwigo
      - traefik.frontend.rule=Host:imagenes.${WO_HOST}
      - traefik.docker.network=web
      - traefik.port=9000
      - traefik.enable=true
    networks:
      - web
      - default

  mysql:
    image: mysql:5
    volumes:
      - ${WO_DIR_MYSQL}:/var/lib/mysql
    environment:
      MYSQL_USER: "piwigo"
      MYSQL_PASSWORD: "piwigo"
      MYSQL_DATABASE: "piwigo"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
